### Machine Learning - Capstone Project 1
### Singapore Housing Resale Price Prediction
### 01 - Data Collection & Analysis

In [1]:
# Import required libraies
import pandas as pd

In [2]:
dataset = pd.read_csv("Dataset-Singapore-HDB.csv")

In [3]:
# shape property will give the (rows x columns) of the dataset
# This dataset has 232,188 rows and 15 columns
dataset.shape

(232188, 15)

In [4]:
# Give all columns
dataset.columns

Index(['month', 'town', 'flat_type', 'block', 'street_name', 'storey_range',
       'floor_area_sqm', 'floor_area_sqft', 'flat_model',
       'lease_commence_date', 'house_age', 'remaining_lease', 'price_per_sqm',
       'price_per_sqft', 'resale_price'],
      dtype='str')

In [5]:
# .info() method shows the Null/Not-Null counts as well as the data type of the columns
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 232188 entries, 0 to 232187
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   month                232188 non-null  str
 1   town                 232188 non-null  str
 2   flat_type            232188 non-null  str
 3   block                232188 non-null  str
 4   street_name          232188 non-null  str
 5   storey_range         232188 non-null  str
 6   floor_area_sqm       232188 non-null  float64
 7   floor_area_sqft      232188 non-null  float64
 8   flat_model           232188 non-null  str
 9   lease_commence_date  232188 non-null  int64
 10  house_age            232188 non-null  int64
 11  remaining_lease      232188 non-null  str
 12  price_per_sqm        232188 non-null  float64
 13  price_per_sqft       232188 non-null  float64
 14  resale_price         232188 non-null  float64
dtypes: float64(5), int64(2), str(8)
memory usage: 42.9 MB

In [6]:
# Describe the Mean, Standard Deviation, Min, Max and IQR values
dataset.describe()

,floor_area_sqm,floor_area_sqft,lease_commence_date,house_age,price_per_sqm,price_per_sqft,resale_price
count,232188.000000,232188.00000,232188.000000,232188.000000,232188.000000,232188.000000,2.321880e+05
mean,96.702159,1040.89237,1996.530105,29.469895,5544.755564,515.125146,5.303231e+05
std,24.016161,258.50756,14.352751,14.352751,1650.593707,153.345322,1.897678e+05
min,31.000000,333.68090,1966.000000,4.000000,2089.552239,194.125943,1.400000e+05
25%,81.000000,871.87590,1985.000000,14.000000,4376.237624,406.566172,3.900000e+05
50%,93.000000,1001.04270,1997.000000,29.000000,5268.817204,489.489609,5.000000e+05
75%,112.000000,1205.55680,2012.000000,41.000000,6301.369863,585.416983,6.380000e+05
max,366.700000,3947.12213,2022.000000,60.000000,16148.936170,1500.286715,1.728000e+06

In [7]:
# First 5 records
dataset.head(5)

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,floor_area_sqft,flat_model,lease_commence_date,house_age,remaining_lease,price_per_sqm,price_per_sqft,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,473.6116,Improved,1979,47,61 years 04 months,5272.727273,489.852867,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,721.1813,New Generation,1978,48,60 years 07 months,3731.343284,346.653470,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,721.1813,New Generation,1980,46,62 years 05 months,3910.447761,363.292836,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,731.9452,New Generation,1980,46,62 years 01 month,3897.058824,362.048962,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,721.1813,New Generation,1980,46,62 years 05 months,3955.223881,367.452678,265000.0

---

In [8]:
from hopelib import HDB
hdb = HDB(dataset)

Initialize HDB class .....

In [12]:
# Get all towns in the dataset
hdb.get_all_towns()

['ANG MO KIO',
 'BEDOK',
 'BISHAN',
 'BUKIT BATOK',
 'BUKIT MERAH',
 'BUKIT PANJANG',
 'BUKIT TIMAH',
 'CENTRAL AREA',
 'CHOA CHU KANG',
 'CLEMENTI',
 'GEYLANG',
 'HOUGANG',
 'JURONG EAST',
 'JURONG WEST',
 'KALLANG/WHAMPOA',
 'MARINE PARADE',
 'PASIR RIS',
 'PUNGGOL',
 'QUEENSTOWN',
 'SEMBAWANG',
 'SENGKANG',
 'SERANGOON',
 'TAMPINES',
 'TOA PAYOH',
 'WOODLANDS',
 'YISHUN']

In [13]:
# Get all flat types
hdb.get_flat_types()

['2 ROOM',
 '3 ROOM',
 '4 ROOM',
 '5 ROOM',
 'EXECUTIVE',
 '1 ROOM',
 'MULTI-GENERATION']

In [14]:
# Get flat models
hdb.get_flat_models()

['Improved',
 'New Generation',
 'DBSS',
 'Standard',
 'Apartment',
 'Simplified',
 'Model A',
 'Premium Apartment',
 'Adjoined flat',
 'Model A-Maisonette',
 'Maisonette',
 'Type S1',
 'Type S2',
 'Model A2',
 'Terrace',
 'Improved-Maisonette',
 'Premium Maisonette',
 'Multi Generation',
 'Premium Apartment Loft',
 '2-room',
 '3Gen']

In [15]:
# Grab the dataset for particular town only
bukit_batok_dataset = hdb.get_dataset_by_town("BUKIT BATOK")

In [16]:
bukit_batok_dataset.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,floor_area_sqft,flat_model,lease_commence_date,house_age,remaining_lease,price_per_sqm,price_per_sqft,resale_price
148,2017-01,BUKIT BATOK,3 ROOM,342,BT BATOK ST 34,01 TO 03,64.0,688.8896,Simplified,1987,39,69 years 11 months,3984.375000,370.160908,255000.0
149,2017-01,BUKIT BATOK,3 ROOM,530,BT BATOK ST 51,04 TO 06,64.0,688.8896,Simplified,1987,39,69 years 06 months,3984.375000,370.160908,255000.0
150,2017-01,BUKIT BATOK,3 ROOM,145,BT BATOK ST 11,04 TO 06,68.0,731.9452,New Generation,1984,42,66 years 05 months,3823.529412,355.217850,260000.0
151,2017-01,BUKIT BATOK,3 ROOM,528,BT BATOK ST 51,10 TO 12,60.0,645.8340,Improved,1987,39,69 years 06 months,4333.333333,402.580230,260000.0
152,2017-01,BUKIT BATOK,3 ROOM,537,BT BATOK ST 52,01 TO 03,73.0,785.7647,Model A,1987,39,69 years 04 months,3561.643836,330.887860,260000.0

In [17]:
# Average price in the town
price = hdb.get_average_price_by_town('BUKIT BATOK')
print("Average price in BUKIT BATOK: S$", round(price, 2))

Average price in BUKIT BATOK: S$ 507369.82

In [18]:
price = hdb.get_average_price_by_town('QUEENSTOWN')
print("Average price in QUEENSTOWN: S$", round(price, 2))

Average price in QUEENSTOWN: S$ 644124.51

In [19]:
# Highest price in the town
highest_price = hdb.get_highest_price_by_town('BUKIT BATOK')
print("Highest price in BUKIT BATOK: S$", round(highest_price, 2))

Highest price in BUKIT BATOK: S$ 1180000.0

In [20]:
# Lowest price in the town
highest_price = hdb.get_lowest_price_by_town('BUKIT BATOK')
print("Lowest price in BUKIT BATOK: S$", round(highest_price, 2))

Lowest price in BUKIT BATOK: S$ 208000.0

In [21]:
# Get available story range
storey_ranges = hdb.get_storey_ranges()
storey_ranges

['10 TO 12',
 '01 TO 03',
 '04 TO 06',
 '07 TO 09',
 '13 TO 15',
 '19 TO 21',
 '22 TO 24',
 '16 TO 18',
 '34 TO 36',
 '28 TO 30',
 '37 TO 39',
 '49 TO 51',
 '25 TO 27',
 '40 TO 42',
 '31 TO 33',
 '46 TO 48',
 '43 TO 45']