### Machine Learning - Capstone Project 1
### Singapore Housing Resale Price Prediction
### 03 - Deployment Phase

In [1]:
# Import required libraies
import pandas as pd
import pickle

In [2]:
# Prepare user data
input_data = {
    "town": "BUKIT BATOK",
    "flat_type": "4 ROOM",
    "storey_range": "10 TO 12",
    "floor_area_sqm": 100,
    "flat_model": "Model A",
    "lease_commence_date": 2000,
    "house_age": 26,
    "price_per_sqm": 5500,
    "price_per_sqft": 500
}

input_data_df = pd.DataFrame([input_data])

In [3]:
input_data_df

,town,flat_type,storey_range,floor_area_sqm,flat_model,lease_commence_date,house_age,price_per_sqm,price_per_sqft
0,BUKIT BATOK,4 ROOM,10 TO 12,100,Model A,2000,26,5500,500

In [4]:
training_columns = pickle.load(open("hdb_training_columns.sav", "rb"))
input_data_df = input_data_df.reindex(columns=training_columns, fill_value=0)

In [5]:
input_data_df

,floor_area_sqm,floor_area_sqft,lease_commence_date,house_age,price_per_sqm,price_per_sqft,town_BEDOK,town_BISHAN,town_BUKIT BATOK,town_BUKIT MERAH,...,flat_model_Multi Generation,flat_model_New Generation,flat_model_Premium Apartment,flat_model_Premium Apartment Loft,flat_model_Premium Maisonette,flat_model_Simplified,flat_model_Standard,flat_model_Terrace,flat_model_Type S1,flat_model_Type S2
0,100,0,2000,26,5500,500,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
scaler_x = pickle.load(open("hdb_scaler_x.sav", "rb"))
scaler_y = pickle.load(open("hdb_scaler_y.sav", "rb"))

In [12]:
scaler_x

StandardScaler()

In [13]:
scaler_y

StandardScaler()

In [14]:
scaled_data_x = scaler_x.transform(input_data_df)

In [15]:
scaled_data_x

array([[ 0.13954337, -4.021859  ,  0.24292298, -0.24292298, -0.02620113,
        -0.09765822, -0.23437193, -0.1326932 , -0.2104665 , -0.19900465,
        -0.19227059, -0.04850529, -0.08913009, -0.21725248, -0.15032972,
        -0.15979628, -0.23144321, -0.14395198, -0.26593691, -0.17784607,
        -0.07896288, -0.17137974, -0.2791373 , -0.16739424, -0.1776688 ,
        -0.29697117, -0.13444697, -0.27159066, -0.1834863 , -0.27641634,
        -0.26973484, -0.14654123, -0.56042548, -0.85733576, -0.56904055,
        -0.27641634, -0.01969183, -0.54501123, -0.51453838, -0.48094353,
        -0.32677409, -0.21693978, -0.14125974, -0.11800317, -0.09253433,
        -0.07467267, -0.05528489, -0.05257387, -0.04686074, -0.0325836 ,
        -0.01870976, -0.01521669, -0.00928142, -0.01955455, -0.04154177,
        -0.1926316 , -0.1280593 , -0.56794626, -0.01227856, -0.16700296,
        -0.74767956, -0.04134625, -0.10701083, -0.01969183, -0.37362885,
        -0.35083129, -0.02423128, -0.00956709, -0.19977818, -0.16575563,
        -0.02273963, -0.04022048, -0.02917756]])

In [7]:
# Load the finalized model
model = pickle.load(open("hdb_model_rf.sav", "rb"))

In [8]:
model

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=1,
             param_grid={'criterion': ['squared_error', 'friedman_mse'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 25, 50]},
             verbose=3)

In [20]:
price = model.predict(scaled_data_x)
price

array([-0.51107495])

In [21]:
price.shape

(1,)

In [25]:
inversed_price = scaler_y.inverse_transform(price.reshape(-1, 1))
inversed_price

array([[432833.28]])

In [30]:
inversed_price.shape

(1, 1)

In [31]:
inversed_price.item()

432833.28

In [32]:
print(
    input_data["town"],  
    input_data["flat_type"], 
    input_data["storey_range"], 
    input_data["flat_model"], 
    input_data["lease_commence_date"], 
    "predicted price is", inversed_price.item())

BUKIT BATOK 4 ROOM 10 TO 12 Model A 2000 predicted price is 432833.28

### Deploy in Django

In [ ]:
# https://varatharuban.pythonanywhere.com/housing/

In [29]:
# Application has deployed in Django Web Application. Please visit above URL to live testing